import * as React from 'react';
import { Box, } from '@mui/material';
import { Form, Row, Col, } from 'react-bootstrap';
import { useState } from 'react';
import { format } from 'date-fns'

const ViewQuotation = ({ theViewQuotation }) => {
    const [discount] = useState(theViewQuotation.discount);
    const [tax] = useState(theViewQuotation.gst);
    const [gsQuantity] = useState(theViewQuotation.gsQuantity);
    const [installments] = useState(theViewQuotation.instalments);
    const [amount] = useState(theViewQuotation.amount);
    const [remarks] = useState(theViewQuotation.remarks);
    const [bankDetails] = useState(theViewQuotation.bankDetails);
    const subtotal = (gsQuantity * amount);
    const taxRate = (tax * subtotal) / 100;
    const discountRate = (discount * subtotal) / 100;
    const total = (subtotal - discountRate + taxRate)
    const quotationDate = format(new Date(theViewQuotation.quotationDate), 'mm/dd/yyyy')

    return (
        <Box sx={{ flexGrow: 1 }} style={{ 'borderRadius': '5px' }}>
            <Form className='mt-2 ml-2 mr-2'>
                <Row>
                    <Col md="7">
                        <img
                            sizes="12px"
                            src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjhVskpYXfF31NyGSjgoPfjnS6qH8TY8wWftKfux4&s"
                        ></img>
                    </Col>
                    <Col>
                        <h5 style={{ "color": "MidnightBlue" }}>
                            MENTOR PARTH LEAD CRM
                        </h5>
                        <span>Haware Fantasia Business Park</span>
                        <br />
                        <span>Vashi, Navi Mumbai-402107</span>
                        <br />
                        <span>Company Reg. No :-896522147</span>
                        <br />
                        <span className="font-bold">GST No: {theViewQuotation.gstNo}</span>
                        {/* <br /> */}
                        {/* <span className="font-bold">State: {theViewQuotation.companyStateName}</span> */}
                        <br />
                        <span className="font-bold">Email: {theViewQuotation.companyEmail}</span>
                    </Col>
                </Row>
                <br /> <br />
                <table className="table table-striped table-bordered" style={{ 'borderRadius': '2px' }}>
                    <thead style={{ 'border - left': '1px solid red', "color": "MidnightBlue", 'border-right': '1px solid red' }} className='text-left'>
                        <tr>
                            <th>Billing Information</th>
                            <th>Quotation Details</th>
                        </tr>
                    </thead>
                    <tbody >
                        <tr>
                            <td width="60%" className='text-left'> <span>Name   &nbsp;&nbsp;&nbsp;:   {theViewQuotation.billTo}</span>
                                <br />
                                <span className="font-bold">GST NO  :   {theViewQuotation.gstNo}</span>
                                <br />
                                <span className="font-bold">PAN No  :   {theViewQuotation.panNo}</span>
                                <br />
                                <span className="font-bold">Contact :   {theViewQuotation.clientContact}</span>
                                <br />
                                <span className="font-bold">Email&nbsp;&nbsp;&nbsp;&nbsp;  :   {theViewQuotation.clientEmail}</span></td>
                            <td className='text-left'>
                                <span>Quotation No  :    </span>
                                <b style={{ "color": "MidnightBlue" }}>{theViewQuotation.quotationNumber}</b>
                                <br />
                                <span className="font-bold">Date    :   {quotationDate}</span>
                                <br />
                                <span className="font-bold">Generated By    : {theViewQuotation.cashierName}</span>
                                <br />
                                <span className="font-bold">Refrence No. & Date:</span>
                            </td>
                        </tr>
                        <tr>
                            <td><span>Address   :   {theViewQuotation.clientAddress}</span></td>
                        </tr>
                        <tr>
                            <td>
                                <span>Bank Details   :   {bankDetails}</span><br />
                                <span>Account No   :   {bankDetails}</span><br />
                                <span>IFSC Code   :   {bankDetails}</span>
                            </td>
                            <td>
                                <span>Payment Mode   :   {bankDetails}</span><br />
                                <span>No. of EMI  :   {Object.keys(installments).length}</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <h5 className='text-center'> PRODUCT INFORMATION </h5>
                <table className="table table-striped table-bordered" style={{ 'borderRadius': '2px' }}>
                    <thead style={{ 'border - left': '1px solid red', "color": "MidnightBlue", 'border-right': '1px solid red' }} className='text-center'>
                        <tr>
                            <th>Discription</th>
                            <th>Quantity</th>
                            <th>Unit Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    {/* {APIData.map((quotation, index) => { */}
                    <tbody className='text-center'>
                        <tr>
                            {/* <td>{theViewQuotation.gsCatalogueId}</td> */}
                            <td>Equity</td>
                            <td>{theViewQuotation.gsQuantity}</td>
                            <td>{theViewQuotation.amount}</td>
                            <td>{subtotal}</td>
                        </tr>
                    </tbody>
                    {/* })} */}
                </table>
                <Row>
                    <Col md="8">
                    </Col>
                    <Col>
                        <b><Form.Label>Subtotal :</Form.Label></b>
                        <Form.Label style={{ color: 'green' }} className="ml-2">
                            ₹ {subtotal}
                        </Form.Label>
                    </Col>
                </Row>
                <Row>
                    <Col md="8">
                    </Col>
                    <Col>
                        <b><Form.Label>Tax ({tax}%) :</Form.Label></b>
                        <Form.Label style={{ color: 'green' }} className="ml-2">
                            ₹ {taxRate}
                        </Form.Label>
                    </Col>
                </Row>
                <Row>
                    <Col md="8">
                    </Col>
                    <Col>
                        <b><Form.Label>Discount ({discount}%) :</Form.Label></b>
                        <Form.Label style={{ color: 'green' }} className="ml-2">
                            ₹ {discountRate}
                        </Form.Label>
                    </Col>
                </Row>
                <Row>
                    <Col md="8">
                    </Col>
                    <Col>
                        <hr />
                        <b><Form.Label>Grand Total :</Form.Label></b>
                        <Form.Label style={{ color: 'green' }} className="ml-2">
                            ₹ {total}
                        </Form.Label>
                    </Col>
                </Row>
                <br />
                {/* hide amd show condition */}
                {Object.keys(installments).length > 0 ? (
                    <div>
                        < h5 style={{ "color": "MidnightBlue" }}>Installment Information</h5>
                        <Row>
                            <Col>
                                <b><Form.Label>No. of Installment : </Form.Label></b>
                                <Form.Label style={{ color: 'green' }} className="ml-2">
                                    {Object.keys(installments).length}
                                </Form.Label>
                            </Col>
                            <Col>
                            </Col>
                        </Row></div>

                ) : (
                    <div></div>
                )}
                {/* hide amd show condition */}
                {Object.keys(installments).length > 0 ? (
                    <table className="table table-striped table-bordered text-center" style={{ 'borderRadius': '2px' }}>
                        <thead style={{ 'border - left': '1px solid red', "color": "MidnightBlue", 'border-right': '1px solid red' }}>
                            <tr >
                                <th>Sr.No</th>
                                <th>Amount</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody >
                            {installments.map((emi, index) => {
                                return (
                                    <tr key={index}>
                                        <td>{emi.instalmentNumber} </td>
                                        <td>{emi.instalmentAmount}</td>
                                        <td>{format(new Date(emi.instalmentDate), 'mm/dd/yyyy')} </td>

                                    </tr>
                                );
                            })}
                        </tbody>
                    </table>
                ) : (
                    <div></div>
                )}
                {/* hide amd show condition */}
                {remarks != '' ? (
                    <div>
                        <h5 style={{ "color": "MidnightBlue" }}>Remarks</h5>
                        <Row>
                            <Col> <span style={{ "color": "red" }}>{remarks}</span></Col>
                        </Row>
                    </div>
                ) : (
                    <div></div>
                )}
            </Form>
        </Box >
    );
};

export default ViewQuotation;
